// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifhivlnvgnbfopwzcwyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmaGl2bG52Z25iZm9wd3pjd3liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMTk3NzUsImV4cCI6MjA3MDU5NTc3NX0.22HwNppJALkzifNpqHShJDjCQJtWJeE91iN76VUr6qs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});